/// Flutter icons Custom_icons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom_icons
///      fonts:
///       - asset: fonts/Custom_icons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Custom_icons {
  Custom_icons._();

  static const _kFontFam = 'Custom_icons';
  static const String? _kFontPkg = null;

  static const IconData message = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
